### PR TITLE
VS 2017 compatibility

### PR DESCRIPTION
**Pull request by b-**
Fixes compilation with VS 2017, as well as VS 2017 + Mono. Fix found as per https://visualstudio2010yahya5.blogspot.com.ng/2017/03/vs-2017-bug-or-new-features.html

### CODE REVIEW

**Review by Falco20019 — CHANGES_REQUESTED** [review]
Please leave the namespace and signature stuff intact

**Comment by Falco20019** [comment]
What exactly is the problem with VS2017?

**Comment by zephster** [comment]
The issue is the `for ` loop in the `StringToByteArrayFastest `method. Just adding the parenthesis around `hex.Length >> 1` fixes it for me.
 The actual error is `CS0118 'hex' is a variable but is used like a type`

**Comment by Falco20019** [comment]
Thanks for the notice @zephster! Will fix it in the next version, especially for the netstandard version

**Pull request closed without merging**
